services:
  # Config Server
  config-server:
    image: rjtdessai18/config-server:0.0.1-SNAPSHOT
    container_name: config-server
    ports:
      - 8888:8888
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - scaler

  # MySQL DB
  product-service-db:
    image: mysql:latest
    container_name: product-service-db
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_service_db
    networks:
      - scaler

  # Redis Cache
  redis-service:
    image: redis:alpine
    container_name: redis-service
    restart: always
    ports:
      - 6379:6379
    networks:
      - scaler

  # Elasticsearch
  elasticsearch:
    image: elasticsearch:8.8.0
    hostname: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - scaler

  # ProductService
  product-service:
    image: rjtdessai18/product-service:0.0.1-SNAPSHOT
    container_name: product-service
    ports:
      - 8081:8081
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      config-server:
        condition: service_completed_successfully
      product-service-db:
        condition: service_healthy
    networks:
      - scaler
    environment:
      SPRING_APPLICATION_NAME: ProductService
      SERVER_PORT: 8081
      SPRING_CONFIG_IMPORT: http://config-server:8888/
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://product-service-db:3306/product_service_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis-service
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_ELASTICSEARCH_CONNECTIONURL: elasticsearch:9200

networks:
  scaler:
    driver: bridge